const modules = [
  {
    name: "Programming 100",
    order: 1,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Join Alex and Lonnie as they design some fancy, fishy creations.",
    courseName: "Foundation skills 1",
  },
  {
    name: "Programming 0",
    order: 3,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Join Alex and Lonnie as they learn about coding by creating fun, interactive pictures. Learn about sequence, loops, events, and actions as you create crazy creatures in this exciting adventure!",
    courseName: "Foundation skills 1",
  },
  {
    name: "Computational Thinking 200",
    order: 5,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Join Cody and Ava as they learn about Data Representation using a fun and interactive DJ Device. Discover how your name can be represented using numbers, images and sound while creating your very own colorful musical melody!",
    courseName: "Foundation skills 1",
  },
  {
    name: "Data Representation 1",
    order: 2,
    lessonsDuration: "3 hrs 20 mins",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "3 hrs 20 mins",
    description:
      "Join Ava and Cody as they help Aunt Kate set up a carnival. Learn how to find patterns in data with sorting, counting, and diagrams.",
    courseName: "Foundation skills 1",
  },
  {
    name: "Computational Thinking 1",
    order: 4,
    lessonsDuration: "3 hrs 20 mins",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "3 hrs 20 mins",
    description:
      "Join Tilley and Charlie on their adventure to get to Pango Rangi Campsite. Will they get there and see the shooting stars? Learn about how algorithms can be used to solve problems by breaking things down into ordered steps as you help them on their journey.",
    courseName: "Foundation skills 1",
  },
  {
    name: "Programming 1",
    order: 6,
    lessonsDuration: "3 hrs 20 mins",
    projectsDuration: "1 hour",
    quizzesDuration: "0",
    totalDuration: "4 hrs 20 mins",
    description:
      "Join Alex and Lonnie on a class field trip to the beach. Find out what happened and why they’re friends again. Learn about programming instructions, animating pictures, and finding bugs as you help them to retell the story.",
    courseName: "Foundation skills 1",
  },
  {
    name: "Data Represenation 2",
    order: 3,
    lessonsDuration: "3 hrs 20 mins",
    projectsDuration: "1 hour",
    quizzesDuration: "0",
    totalDuration: "4 hrs 20 mins",
    description:
      "Join Cody and Ava at the Museum of Communication Technology as they explore the different ways that human communication can be represented with data. Along the way you'll uncover hidden clues that reveal a mysterious secret...",
    courseName: "Foundation skills 2",
  },
  {
    name: "Computational Thinking 2",
    order: 1,
    lessonsDuration: "3 hrs 20 mins",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "3 hrs 20 mins",
    description:
      "There are some very strange goings on at this zoo! Join Tilley and Charlie as they investigate. Develop your logic skills and learn how to make the best decisions. Can you help them discover what’s behind the “Restricted Access” door?",
    courseName: "Foundation skills 2",
  },
  {
    name: "Programming 2",
    order: 2,
    lessonsDuration: "3 hrs 20 mins",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "3 hrs 20 mins",
    description:
      "If more falls and scrapes happen the teachers are threatening to close the bike park! Join Alex and Lonnie as they use the creativity of computer programs to design interactive safety apps and quizzes. Learn how to develop powerful programs by using selection to make decisions with your code.",
    courseName: "Foundation skills 2",
  },
  {
    name: "Programming 3",
    order: 4,
    lessonsDuration: "3 hrs 20 mins",
    projectsDuration: "1 hr",
    quizzesDuration: "0",
    totalDuration: "4 hrs 20 mins",
    description:
      "Alex and Lonnie are on holiday in Finland. During their stay, they find out that Alex's mom, Leena, has inherited an old castle. Leena thinks the castle would make a great tourist attraction, and Alex and Lonnie decide they should make an app. Join them to find out whether they can face the dangers that lie hidden in the castle. Will they solve the mystery and get their app ready for opening day?",
    courseName: "Foundation skills 2",
  },
  {
    name: "Programming 300",
    order: 5,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Alex and Lonnie are on holiday in Finland. During their stay, they find out that Alex's mom, Leena, has inherited an old castle. Leena thinks the castle would make a great tourist attraction, and Alex and Lonnie decide they should make an app. Join them to find out whether they can face the dangers that lie hidden in the castle. Will they solve the mystery and get their app ready for opening day?",
    courseName: "Foundation skills 2",
  },
  {
    name: "JavaScript 123",
    order: 6,
    lessonsDuration: "1 hr 20 mins",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr 20 mins",
    description:
      "Alex and Lonnie are on holiday in Finland. During their stay, they find out that Alex's mom, Leena, has inherited an old castle. Leena thinks the castle would make a great tourist attraction, and Alex and Lonnie decide they should make an app. Join them to find out whether they can face the dangers that lie hidden in the castle. Will they solve the mystery and get their app ready for opening day?",
    courseName: "Foundation skills 2",
  },
  {
    name: "Computational Thinking 300",
    order: 1,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Join Tilley and Charlie as they decorate the Food Avengers restaurant using algorithms.",
    courseName: "Foundation skills 3",
  },
  {
    name: "Computational Thinking 3",
    order: 2,
    lessonsDuration: "4 hrs",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "4 hrs",
    description:
      "Tilley and Charlie’s dad recently started a restaurant called Food Avengers. However, there are concerns that the restaurant's high-tech waiter robot called Ross is actually a health and safety hazard! While Dad is at a business conference, Tilley comes up with an audacious plan to turn things around and make Food Avengers a big success. Together, Charlie and Tilley make many positive changes to the restaurant, but will it be enough?",
    courseName: "Foundation skills 3",
  },
  {
    name: "Impacts of Computing 300",
    order: 3,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Join Sakura and Niko as they learn about security and hacking.",
    courseName: "Foundation skills 3",
  },
  {
    name: "Digital Media 300",
    order: 4,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Join Charlie and Tilley as they design a sport-themed platform game for Lucy's birthday.",
    courseName: "Foundation skills 3",
  },
  {
    name: "Data Representation 200",
    order: 5,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Join Cody and Ava as they learn about Data Representation using a fun and interactive DJ Device. Discover how your name can be represented using numbers, images and sound while creating your very own colorful musical melody!",
    courseName: "Foundation skills 3",
  },
  {
    name: "JavaScript 103",
    order: 6,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Drawing with JavaScript is easier than you might think. Learn more about the flags of the world as each level increases in complexity. Learn about shapes, coordinates, colors as well as the importance of sequence in coding.",
    courseName: "Foundation skills 3",
  },
  {
    name: "JavaScript 105",
    order: 7,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "This is your first step on the way to becoming a game development master. This course will gently guide you through building a simple 2D top-down game you can play with your friends. Along the way, you’ll learn about coordinates and hunt bugs as you prepare for the more complex work to come.",
    courseName: "Foundation skills 3",
  },
  {
    name: "Impacts of Computing 600",
    order: 8,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "AVATAR is the latest interactive attraction at ThrillVille theme park. Sakura and Niko can't wait to visit it and experience the world of tomorrow! Join Sakura and Niko as they learn about data, digital footprints, the Internet of things, Big Data, and the implications these have for us as people, and our future.",
    courseName: "Foundation skills 3",
  },
  {
    name: "Networks & Security 600",
    order: 9,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Join Max and his friends at the skate park. Felix posts a seemingly innocent photo of Juno on social media, that she desperately wants to have removed. Max, who has a spy movie obsession, is quick to turn the situation into a secret mission. Join them as they learn about cloud computing and track down the photo on a server, stored in an ultra-secure data center. Is there any way to locate and destroy the photo?",
    courseName: "Foundation skills 3",
  },
  {
    name: "Data and Analysis 60",
    order: 10,
    lessonsDuration: "2 hrs",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "2 hrs",
    description:
      "Collect, analyze and present data using Google Forms and Sheets.",
    courseName: "Foundation skills 3",
  },
  {
    name: "HTML/CSS 101",
    order: 1,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Starting to learn HTML and CSS is easy and fun with this digital postcard. Learn about adding headings, paragraphs, images, and links to create a holiday card or birthday celebration to share with friends and family.",
    courseName: "Foundation skills 4",
  },
  {
    name: "Algorithms 0",
    order: 2,
    lessonsDuration: "3 hrs",
    projectsDuration: "0",
    quizzesDuration: "15 mins",
    totalDuration: "3 hrs 15 mins",
    description:
      "Algorithms are the steps we use to solve problems, so they are a really important part of programming and computer science. In this course you'll learn about what algorithms are, how to create them, different types of algorithms, and how to determine the best algorithm to use for particular problem.",
    courseName: "Foundation skills 4",
  },
  {
    name: "JavaScript 0",
    order: 3,
    lessonsDuration: "2 hrs",
    projectsDuration: "2 hrs",
    quizzesDuration: "0",
    totalDuration: "4 hrs",
    description:
      "Want to build your own apps and games? Start here! With Code Avengers' comprehensive JavaScript courses you'll learn one of the most widely used languages, and build lots of fun apps and games along the way.",
    courseName: "Foundation skills 4",
  },
  {
    name: "Data Representation 400",
    order: 4,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Join Tyrell and Marlee as they learn about binary numbers, light, color and more while trying to escape from Professor Photon's Color Conundrum",
    courseName: "Foundation skills 4",
  },
  {
    name: "Python 100",
    order: 5,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Python is an engaging and simple language to learn. Learn about using modules, functions, loops, and lists, all while creating fun images with the help of your turtle buddies. Geometry has never been so much fun!",
    courseName: "Foundation skills 4",
  },
  {
    name: "Python 0",
    order: 6,
    lessonsDuration: "2 hrs",
    projectsDuration: "2 hrs",
    quizzesDuration: "0",
    totalDuration: "4 hrs",
    description:
      "Use a range of Python skills such as input, output, variables, if statements, turtles and loops to build a basic program.",
    courseName: "Foundation skills 4",
  },
  {
    name: "Digital Infrastructure 4",
    order: 3,
    lessonsDuration: "3 hrs",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "3 hrs",
    description:
      "Join Juno and Max as they follow the data trail of a mysterious message appearing on their high school’s network system and Principal’s cell phone. Learn about network components and the characteristics and communication rules of cellular networks, as you investigate along with them to unravel the message.",
    courseName: "Foundation skills 5",
  },
  {
    name: "Programming 4",
    order: 1,
    lessonsDuration: "3 hrs",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "3 hrs",
    description:
      "The school production starts in 2 days, but there’s been a disaster! Will you be able to help Alex and Lonnie to use their programming skills to solve all of the challenges that come up? You’ll learn about animating scenes using loops and user input, creating apps that respond to mouse clicks, and more. The show must go on!",
    courseName: "Foundation skills 5",
  },
  {
    name: "Impacts of Computing 400",
    order: 2,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Join Sakura and Niko as they learn about how artificial intelligence, drones, and other digital technologies are used on the farms of the future, today.",
    courseName: "Foundation skills 5",
  },
  {
    name: "JavaScript 110",
    order: 4,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "Want to build your own apps and games? Start here! With Code Avengers' comprehensive JavaScript courses you'll learn one of the most widely used languages, and build lots of fun apps and games along the way.",
    courseName: "Foundation skills 5",
  },
  {
    name: "Web Development 100",
    order: 5,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "This challenging and exciting project will teach you how to create a Photo Booth app. Using JavaScript, CSS, and HTML, you will connect buttons that let you use a camera, upload images, and customize your photos by inserting stickers and applying filters.",
    courseName: "Foundation skills 5",
  },
  {
    name: "Web Development 0",
    order: 6,
    lessonsDuration: "3 hrs",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "3 hrs",
    description:
      "Using the skills you’ve learned from our other intro courses, learn how to use HTML, CSS and JavaScript together in one project. Make a ringer app, a quiz using variables to keep score, and turn your phone into a musical instrument by building a xylophone app!",
    courseName: "Foundation skills 5",
  },
  {
    name: "jQuery 0",
    order: 7,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "An essential part of web development is making sites dynamic and interactive. Good thing there's jQuery - a JavaScript library that makes it easy! jQuery lets you write JavaScript tasks in a much more quick and simple way. Just ask Google, Microsoft and Netflix, who all use it. Start learning today, the Code Avengers way!",
    courseName: "Foundation skills 5",
  },
  {
    name: "JavaScript 105",
    order: 1,
    lessonsDuration: "1 hr",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "1 hr",
    description:
      "This is your first step on the way to becoming a game development master. This course will gently guide you through building a simple 2D top-down game you can play with your friends. Along the way, you’ll learn about coordinates and hunt bugs as you prepare for the more complex work to come.",
    courseName: "Game development 1",
  },
  {
    name: "JavaScript 0",
    order: 2,
    lessonsDuration: "2 hrs",
    projectsDuration: "2 hrs",
    quizzesDuration: "0",
    totalDuration: "4 hrs",
    description:
      "Want to build your own apps and games? Start here! With Code Avengers' comprehensive JavaScript courses you'll learn one of the most widely used languages, and build lots of fun apps and games along the way.",
    courseName: "Game development 1",
  },
  {
    name: "JavaScript 1",
    order: 3,
    lessonsDuration: "10 hrs",
    projectsDuration: "18 hrs",
    quizzesDuration: "4 hrs",
    totalDuration: "32 hrs",
    description:
      "JavaScript programmers are hugely sought after by employers, so it’s valuable to know! Jump straight into building apps and games. Learn about variables, Booleans, if statements and loops while completing various projects, code challenges, bug hunts and robot missions.",
    courseName: "Game development 1",
  },
  {
    name: "Python 0",
    order: 4,
    lessonsDuration: "1 hr",
    projectsDuration: "2 hrs",
    quizzesDuration: "0",
    totalDuration: "3 hrs",
    description:
      "Use a range of Python skills such as input, output, variables, if statements, turtles and loops to build a basic program.",
    courseName: "Game development 1",
  },
  {
    name: "Python 1",
    order: 5,
    lessonsDuration: "7 hrs 30 mins",
    projectsDuration: "7 hrs",
    quizzesDuration: "2 hrs 30 mins",
    totalDuration: "17 hrs",
    description:
      "Start learning to code with Python in this entertaining and informative course. Focus on programming essentials like variables, if statements, Booleans and loops. Create text-based apps and play with turtles to learn how to code graphics!",
    courseName: "Game development 1",
  },
  {
    name: "Human Computer Interaction 1",
    order: 1,
    lessonsDuration: "3 hrs",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "3 hrs",
    description:
      "Discover the science behind how people interact with computers.",
    courseName: "Software Development 1",
  },
  {
    name: "Algorithms 1",
    order: 2,
    lessonsDuration: "2 hrs 30 mins",
    projectsDuration: "0",
    quizzesDuration: "15 mins",
    totalDuration: "2 hrs 45 mins",
    description:
      "Algorithms are the steps we use to solve problems, so they are a really important part of programming and computer science. In this course you'll learn about what algorithms are, how to create them, different types of algorithms, and how to determine the best algorithm to use for particular problem.",
    courseName: "Software Development 1",
  },
  {
    name: "JavaScript 1",
    order: 3,
    lessonsDuration: "10 hrs",
    projectsDuration: "18 hrs",
    quizzesDuration: "4 hrs",
    totalDuration: "32 hrs",
    description:
      "JavaScript programmers are hugely sought after by employers, so it’s valuable to know! Jump straight into building apps and games. Learn about variables, Booleans, if statements and loops while completing various projects, code challenges, bug hunts and robot missions.",
    courseName: "Software Development 1",
  },
  {
    name: "Software Engineering 1",
    order: 4,
    lessonsDuration: "3 hrs 20 mins",
    projectsDuration: "0",
    quizzesDuration: "15 mins",
    totalDuration: "3 hrs 35 mins",
    description:
      "Learn how to write great code by planning your programs. Find out about different methods of planning including flowcharts and pseudocode, as well as how to plan for modular code and graphical user interfaces.",
    courseName: "Software Development 1",
  },
  {
    name: "Python 1",
    order: 5,
    lessonsDuration: "7 hrs 30 mins",
    projectsDuration: "7 hrs",
    quizzesDuration: "2 hrs 30 mins",
    totalDuration: "17 hrs",
    description:
      "Start learning to code with Python in this entertaining and informative course. Focus on programming essentials like variables, if statements, Booleans and loops. Create text-based apps and play with turtles to learn how to code graphics!",
    courseName: "Software Development 1",
  },
  {
    name: "Programming languages 1",
    order: 6,
    lessonsDuration: "4 hrs",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "4 hrs",
    description:
      "What are programming languages and how do we use them? This course will teach you what features they contain, the difference between high level and low level languages, and what a compiler is.",
    courseName: "Software Development 1",
  },
  {
    name: "Digital Systems 1 - How the Web Works",
    order: 1,
    lessonsDuration: "2 hrs 30 mins",
    projectsDuration: "0",
    quizzesDuration: "1 hr 45 mins",
    totalDuration: "4 hrs 15 mins",
    description:
      "You use the internet everyday, but do you know how it works? As you explore the magic behind the web, learn about the tools and resources available to get your own website up and running.",
    courseName: "Web Design 1",
  },
  {
    name: "Design 2 - Color Theory",
    order: 2,
    lessonsDuration: "6 hrs 40 mins",
    projectsDuration: "0",
    quizzesDuration: "2 hrs 30 mins",
    totalDuration: "9 hrs 10 mins",
    description:
      "Discover the science and psychology behind colors and get the edge you need to create impactful designs that get your point across. We’ll teach you the principles of color harmony and contrast, how to choose color schemes with color wheels, the meaning behind all your favorite colors, and much more!",
    courseName: "Web Design 1",
  },
  {
    name: "HTMl/CSS 1",
    order: 3,
    lessonsDuration: "6 hrs 40 mins",
    projectsDuration: "3 hrs",
    quizzesDuration: "4 hrs 15 mins",
    totalDuration: "13 hrs 55 mins",
    description:
      "Build your first website as you learn the essentials of HTML and CSS with Code Avengers! Play with cool effects and customize headers, footers, images and fonts to make your own personal and business profile pages that are uniquely ''''you''''. Your journey to becoming a web developer or designer starts here.",
    courseName: "Web Design 1",
  },
  {
    name: "Design 1 - Typography",
    order: 4,
    lessonsDuration: "6 hrs 40 mins",
    projectsDuration: "0",
    quizzesDuration: "2 hrs 45 mins",
    totalDuration: "9 hrs 25 mins",
    description:
      "Fonts are an essential ingredient in good design. Explore the history of typography and learn how to supercharge your designs with the ''''right'''' font types. Use CSS to present your text with the impact you need, and add special effects to make it come alive!",
    courseName: "Web Design 1",
  },
  {
    name: "Digital Systems 1 - How the Web Works",
    order: 1,
    lessonsDuration: "2 hrs 30 mins",
    projectsDuration: "0",
    quizzesDuration: "1 hr 45 mins",
    totalDuration: "4 hrs 15 mins",
    description:
      "You use the internet everyday, but do you know how it works? As you explore the magic behind the web, learn about the tools and resources available to get your own website up and running.",
    courseName: "Web Development 1",
  },
  {
    name: "HTML/CSS 1",
    order: 2,
    lessonsDuration: "6 hrs 40 mins",
    projectsDuration: "3 hrs",
    quizzesDuration: "4 hrs 15 mins",
    totalDuration: "13 hrs 55 mins",
    description:
      "Build your first website as you learn the essentials of HTML and CSS with Code Avengers! Play with cool effects and customize headers, footers, images and fonts to make your own personal and business profile pages that are uniquely ''''you''''. Your journey to becoming a web developer or designer starts here.",
    courseName: "Web Development 1",
  },
  {
    name: "JavaScript 1",
    order: 3,
    lessonsDuration: "10 hrs",
    projectsDuration: "18 hrs",
    quizzesDuration: "4 hrs",
    totalDuration: "32 hrs",
    description:
      "JavaScript programmers are hugely sought after by employers, so it’s valuable to know! Jump straight into building apps and games. Learn about variables, Booleans, if statements and loops while completing various projects, code challenges, bug hunts and robot missions.",
    courseName: "Web Development 1",
  },
  {
    name: "Web Development 1",
    order: 4,
    lessonsDuration: "6 hrs 40 mins",
    projectsDuration: "4 hrs",
    quizzesDuration: "45 mins",
    totalDuration: "11 hrs 25 mins",
    description:
      "Combine your skills in HTML, CSS and JavaScript and learn to integrate them into a single project. Create effective app user interfaces with HTML form elements, and make them come alive using JavaScript! Enjoy our projects building smart apps like a personality test and even a functional job application for Google.",
    courseName: "Web Development 1",
  },
  {
    name: "JavaScript 2",
    order: 1,
    lessonsDuration: "10 hrs",
    projectsDuration: "8 hrs",
    quizzesDuration: "1 hr 30 mins",
    totalDuration: "19 hrs 30 mins",
    description:
      "Whether you're a hobbyist or a budding web developer, expand your skills in JavaScript with Code Avengers. Become more acquainted with the technical side of the web with ASCII code, before diving head first into making more advanced apps and games than before with the Math object and arrays.",
    courseName: "Game development 2",
  },
  {
    name: "JavaScript 3",
    order: 2,
    lessonsDuration: "6 hrs 15 mins",
    projectsDuration: "8 hrs",
    quizzesDuration: "0",
    totalDuration: "14 hrs 15 mins",
    description:
      "Want to make a graphical tank battle game? How about apps like an interactive whiteboard? We’ll show you how by introducing you to the PaperJS graphics library and teaching code that reacts to mouse clicks and keystrokes. Also awaiting you are 5 lessons on animation!",
    courseName: "Game development 2",
  },
  {
    name: "Python 2",
    order: 3,
    lessonsDuration: "7 hrs 30 mins",
    projectsDuration: "0",
    quizzesDuration: "2 hrs 30 mins",
    totalDuration: "10 hrs",
    description:
      "Expand on what you learned in ''''Level 1''''. There will be more turtle graphics, and cool lessons on using dictionaries, lists, and functions. You’ll use Python to do all sorts of useful things like discount sale items, track your favorite foods, calculate the area of shapes, and even make your own translator.",
    courseName: "Game development 2",
  },
  {
    name: "Python 3",
    order: 4,
    lessonsDuration: "5 hrs",
    projectsDuration: "0",
    quizzesDuration: "30 mins",
    totalDuration: "5 hrs 30 mins",
    description:
      "Graphical User Interfaces (GUI) are important if you want to write programs for other people to use! In this course you'll learn how to use Python's Tkinter module to create a GUI. You'll also learn how to use classes, methods, attributes and objects to make your code more flexible and robust!",
    courseName: "Game development 2",
  },
  {
    name: "HTML/CSS 2",
    order: 1,
    lessonsDuration: "6 hrs 40 mins",
    projectsDuration: "3 hrs",
    quizzesDuration: "3 hrs",
    totalDuration: "12 hrs 40 mins",
    description:
      "Ready to dive deeper into HTML and CSS? What better way to do it than by building a 5 page, interactive travel guide optimized for mobile devices? Code Avengers will take you through it the fun way. Add audio and video to your webpages, make interactive buttons, create an HTML table and discover new ways to code with color.",
    courseName: "Web Design 2",
  },
  {
    name: "HTML/CSS 3",
    order: 2,
    lessonsDuration: "6 hrs 40 mins",
    projectsDuration: "1 hr",
    quizzesDuration: "2 hrs 30 mins",
    totalDuration: "10 hrs 10 mins",
    description:
      "Responsive Web Design makes your website look great on any screen size, so we’ll show you how to use it! Along the way you’ll learn how to use advanced CSS selectors and special layout techniques. Oh, we’ll also introduce you to PHP – a powerful scripting language used to make dynamic websites like Facebook.",
    courseName: "Web Design 2",
  },
  {
    name: "HTML/CSS 2",
    order: 1,
    lessonsDuration: "6 hrs 40 mins",
    projectsDuration: "3 hrs",
    quizzesDuration: "3 hrs",
    totalDuration: "12 hrs 40 mins",
    description:
      "Ready to dive deeper into HTML and CSS? What better way to do it than by building a 5 page, interactive travel guide optimized for mobile devices? Code Avengers will take you through it the fun way. Add audio and video to your webpages, make interactive buttons, create an HTML table and discover new ways to code with color.",
    courseName: "Web Development 2",
  },
  {
    name: "JavaScript 2",
    order: 2,
    lessonsDuration: "10 hrs",
    projectsDuration: "8 hrs",
    quizzesDuration: "1 hr 30 mins",
    totalDuration: "19 hrs 30 mins",
    description:
      "Whether you're a hobbyist or a budding web developer, expand your skills in JavaScript with Code Avengers. Become more acquainted with the technical side of the web with ASCII code, before diving head first into making more advanced apps and games than before with the Math object and arrays.",
    courseName: "Web Development 2",
  },
  {
    name: "Web Development 2",
    order: 3,
    lessonsDuration: "10 hrs",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "10 hrs",
    description:
      "Build on the HTML, CSS and JavaScript skills you learned in level 1. You'll learn about using loops, timers and much more in JavaScript as well as how to use the Firebase realtime database API to create dynamic apps such as a calorie counter, countdown timer and progress blog.",
    courseName: "Web Development 2",
  },
  {
    name: "jQuery 1",
    order: 4,
    lessonsDuration: "6 hrs 40 mins",
    projectsDuration: "4 hrs",
    quizzesDuration: "0",
    totalDuration: "10 hrs 40 mins",
    description:
      "An essential part of web development is making sites dynamic and interactive. Good thing there's jQuery - a JavaScript library that makes it easy! jQuery lets you write JavaScript tasks in a much more quick and simple way. Just ask Google, Microsoft and Netflix, who all use it. Start learning today, the Code Avengers way!",
    courseName: "Web Development 2",
  },
  {
    name: "Web Development 3",
    order: 5,
    lessonsDuration: "6 hrs 40 mins",
    projectsDuration: "0",
    quizzesDuration: "0",
    totalDuration: "6 hrs 40 mins",
    description:
      "In this level 3 course, you will improve your ability to bring your web apps to life. You'll learn about JavaScript features such as using email servers to send mail and using localStorage to save data. You'll even build a fully functional chat app using Firebase.",
    courseName: "Web Development 2",
  },
  {
    name: "HTML/CSS 3",
    order: 6,
    lessonsDuration: "6 hrs 40 mins",
    projectsDuration: "1 hr",
    quizzesDuration: "2 hrs 30 mins",
    totalDuration: "10 hrs 10 mins",
    description:
      "Responsive Web Design makes your website look great on any screen size, so we’ll show you how to use it! Along the way you’ll learn how to use advanced CSS selectors and special layout techniques. Oh, we’ll also introduce you to PHP – a powerful scripting language used to make dynamic websites like Facebook.",
    courseName: "Web Development 2",
  },
  {
    name: "Python 1",
    order: 1,
    lessonsDuration: "7 hrs 30 mins",
    projectsDuration: "7 hrs",
    quizzesDuration: "2 hrs 30 mins",
    totalDuration: "17 hrs",
    description:
      "Start learning to code with Python in this entertaining and informative course. Focus on programming essentials like variables, if statements, Booleans and loops. Create text-based apps and play with turtles to learn how to code graphics!",
    courseName: "ITS-Python",
  },
  {
    name: "Python 2",
    order: 2,
    lessonsDuration: "7 hrs 30 mins",
    projectsDuration: "0",
    quizzesDuration: "2 hrs 30 mins",
    totalDuration: "10 hrs",
    description:
      "Expand on what you learned in ''''Level 1''''. There will be more turtle graphics, and cool lessons on using dictionaries, lists, and functions. You’ll use Python to do all sorts of useful things like discount sale items, track your favorite foods, calculate the area of shapes, and even make your own translator.",
    courseName: "ITS-Python",
  },
  {
    name: "Python 3",
    order: 3,
    lessonsDuration: "5 hrs",
    projectsDuration: "0",
    quizzesDuration: "30 mins",
    totalDuration: "5 hrs 30 mins",
    description:
      "Graphical User Interfaces (GUI) are important if you want to write programs for other people to use! In this course you'll learn how to use Python's Tkinter module to create a GUI. You'll also learn how to use classes, methods, attributes and objects to make your code more flexible and robust!",
    courseName: "ITS-Python",
  },
];
module.exports = {
  modules,
};
